project:
  type: website
  output-dir: ../../docs  # GitHub Pages will serve from here
  title: "First game website"
website: 
  title: Untitled First Game
  navbar:
    search: false
    # tools:
    #   - icon: github
    #     menu:
    #       - text: View on Github
    #         href: https://github.com/niboXR/first-game
    #       - text: Project tasks and timeline
    #         href: https://github.com/users/niboXR/projects/3
    #background: dark
    left:
      - href: game-design-doc.qmd
        text: GDD
  
format:
  html:
    theme: sketchy
    css: default-styles.css
    other-links: 
      - text: View on Github
        href: https://github.com/niboXR/first-game
        icon: github
      - text: Project tasks and timeline
        href: https://github.com/users/niboXR/projects/3
        icon: github
        class: no-icon

    toc: true
    toc-location: left
    # toc-depth: 3
    number-sections: true
    number-depth: 1